apiVersion: multik8s.platformref.crossplane.io/v1alpha1
kind: Network
metadata:
  name: network-aws
spec:
  id: multik8s-network
  clusterRef:
    id: multik8s-cluster
  compositionSelector:
    matchLabels:
      provider: AWS
